# -*- coding: utf-8 -*-
"""TUBES VISDAT BAMBANG

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjAObzt78kTtqaBvYvYtCELah9gcnVkd

**TUGAS BESAR VISUALISASI DATA**

Bambang Silva P
"""

# Import Library
import numpy as np
import pandas as pd
import bokeh
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource, CustomJS
from bokeh.models.widgets.sliders import DateRangeSlider
from bokeh.layouts import row, column, gridplot
from bokeh.models import Slider, Select
from bokeh.io import output_file, output_notebook, curdoc
from bokeh.models.widgets import Tabs, Panel
from bokeh.io import output_file, show

# Module Version
print('Bokeh  Version  : {}'.format(bokeh.__version__))
print('Pandas Version  : {}'.format(pd.__version__))
print('Numpy  Version  : {}'.format(np.__version__))

#Import Dataset
data = pd.read_csv("Data_covid19.csv", parse_dates=['date'])
data.sample(5)

# Add new column
data["Name"] = "Data Covid"
newDS1 = data
newDS1 = newDS1.sort_values(['date', 'Name'])
newDS1.head()
DataCovid = newDS1[newDS1['Name'] == 'Data Covid']
output_notebook()

DataCovid

# Theme Layout 
curdoc().theme = "dark_minimal"

output_notebook()

# Resource Data
output_file('DataCovidViz.html',
            title='Data Covid 19')
dt_covid = ColumnDataSource(DataCovid)


# Hover
tooltips = [('Name', '@Name'), ('acc_confirmed', '@acc_confirmed'), ('new_confirmed', '@new_confirmed'),('acc_negative', '@acc_negative')]
tool=[('new_tested','@new_tested'), ('acc_tested','@acc_tested'),  ('being_checked','@being_checked'),  ('isolated','@isolated')]


#Plot
covidFig = figure(x_axis_type= 'datetime',
                  plot_height=500, plot_width=1000,
                  title='Data Covid 19', 
                  x_axis_label='Dates', y_axis_label='acc confirmed',  tooltips=tooltips)

covidFig2 = figure(x_axis_type= 'datetime',
                  plot_height=500, plot_width=1000,
                  title='Data Covid 19', 
                  x_axis_label='Dates', y_axis_label='new confirmed',  tooltips=tooltips)

covidFig3 = figure(x_axis_type= 'datetime',
                  plot_height=500, plot_width=1000,
                  title='Data Covid 19', 
                  x_axis_label='Dates', y_axis_label='acc negative',  tooltips=tooltips)

covidFig4 = figure(x_axis_type= 'datetime',
                  plot_height=500, plot_width=1000,
                  title='Data Covid 19', 
                  x_axis_label='Dates', y_axis_label='Covid Value',  tooltips=tool)

#Line Plot
covidFig.line('date', 'acc_confirmed', 
         color='red', legend_label='Data Covid 19 - acc_confirmed',
         line_width=2, 
         source=dt_covid)

covidFig2.line('date', 'new_confirmed', 
         color='yellow', legend_label='Data Covid 19 - new_confirmed',
         line_width=2, 
         source=dt_covid)

covidFig3.line('date', 'acc_negative', 
         color='green', legend_label='Data Covid 19 - acc_negative',
         line_width=2, 
         source=dt_covid)


# Select Dropdown
plot_1 = covidFig4.line(x='date', y='new_tested',  color='blue', legend_label='Data Covid 19', line_width=2, source=dt_covid )
plot_2 = covidFig4.line(x='date', y='acc_tested',  color='orange', legend_label='Data Covid 19', line_width=2, source=dt_covid )
plot_3 = covidFig4.line(x='date', y='being_checked',  color='green', legend_label='Data Covid 19', line_width=2, source=dt_covid )
plot_4 = covidFig4.line(x='date', y='isolated',  color='red', legend_label='Data Covid 19', line_width=2, source=dt_covid )

covidFig.legend.location = 'top_left'
covidFig.legend.click_policy = 'hide'

covidFig2.legend.location = 'top_left'
covidFig2.legend.click_policy = 'hide'

covidFig3.legend.location = 'top_left'
covidFig3.legend.click_policy = 'hide'

covidFig4.legend.location = 'top_left'
covidFig4.legend.click_policy = 'hide'



#Slider DateTime
date_slider_acc = DateRangeSlider(value=(min(newDS1['date']), max(newDS1['date'])),
                              start=min(newDS1['date']),end=max(newDS1['date']),width=300)
date_slider_acc.js_link('value', covidFig.x_range, 'start', attr_selector=0)
date_slider_acc.js_link('value', covidFig.x_range, 'end', attr_selector=1)

date_slider_new = DateRangeSlider(value=(min(newDS1['date']), max(newDS1['date'])),
                              start=min(newDS1['date']),end=max(newDS1['date']),width=300)
date_slider_new.js_link('value', covidFig2.x_range, 'start', attr_selector=0)
date_slider_new.js_link('value', covidFig2.x_range, 'end', attr_selector=1)

date_slider_neg = DateRangeSlider(value=(min(newDS1['date']), max(newDS1['date'])),
                              start=min(newDS1['date']),end=max(newDS1['date']),width=300)
date_slider_neg.js_link('value', covidFig3.x_range, 'start', attr_selector=0)
date_slider_neg.js_link('value', covidFig3.x_range, 'end', attr_selector=1)

date_slider_tes = DateRangeSlider(value=(min(newDS1['date']), max(newDS1['date'])),
                              start=min(newDS1['date']),end=max(newDS1['date']),width=300)
date_slider_tes.js_link('value', covidFig4.x_range, 'start', attr_selector=0)
date_slider_tes.js_link('value', covidFig4.x_range, 'end', attr_selector=1)


#Interactive Select List
select = Select(title="Plot to show:", value="new_tested", options=["new_tested", "acc_tested", "being_checked", "isolated"])
select.js_on_change("value", CustomJS(args=dict(new_tested=plot_1, acc_tested=plot_2, being_checked=plot_3,  isolated=plot_4, tooltips=tool), code="""

new_tested.visible = true
acc_tested.visible = true
being_checked.visible = true
isolated.visible = true

if (this.value === "new_tested") {
    acc_tested.visible = false 
    being_checked.visible = false 
    isolated.visible = false 
} else if (this.value === "acc_tested") {
    new_tested.visible = false
    being_checked.visible = false 
    isolated.visible = false 
} else if (this.value === "being_checked") {
    new_tested.visible = false
    acc_tested.visible = false 
    isolated.visible = false 
} else  {
    new_tested.visible = false
    acc_tested.visible = false 
    being_checked.visible = false 
}
    
""")
)

#Tabs
tab1 = row(date_slider_acc, covidFig)
tab2 = row(date_slider_new, covidFig2)
tab3 = row(date_slider_neg, covidFig3)
tab4 = row(date_slider_tes, covidFig4)
tab4 = row(select, covidFig4)

#Show Tabs
panel_1 = Panel(child= tab1, title='Acc Confirmed')
panel_2 = Panel(child= tab2, title='New Confirmed')
panel_3 = Panel(child= tab2, title='Negative')
panel_4 = Panel(child= tab2, title='Other Data')

tabs = Tabs(tabs=[panel_1, panel_2, panel_3, panel_4])

curdoc().add_root(tabs)
show(tabs)